### PR TITLE
Fix TypeScript definitions for xxxOrDefault

### PR DESCRIPTION
**Pull request by ugaya40**
Return type of xxxOrDefault method in TypeScirpt definition seems to be wrong.
The xxxOrDefault method returns **'undefined | T'**, right?

### CODE REVIEW

**Comment by mihaifm** [comment]
Thanks, I'll give this a test and merge it.

**Comment by mihaifm** [comment]
Can you provide a scenario where the undefined would be useful? I can't seem to force the typescript compiler to give any kind of error.

**Comment by ugaya40** [comment]
I wrote the code for the case that returns undefined in StackBlitz. 
https://stackblitz.com/edit/typescript-v9rfe1 
Is this true to the intent of your question?

**Comment by mihaifm** [comment]
Thanks, I am aware that they can return undefined. The question was if it makes any difference to explicitly declare that they can return undefined. For example in typescript I can write this: 

    function f() : number {
      return undefined
    }

...without getting any error. So would it matter if I say add `|undefined` in there ?

    function f() : number | undefined {
       return undefined
    }

Just asking.

**Comment by ugaya40** [comment]
```
function f() : number {
  return undefined
}
```
In the above code, if the strict option (strictly speaking strictNullChecks) is true, an error will occur.

Typically, in TypeScript projects, strict is set to true.

TypeScript Playground Code:  
https://www.typescriptlang.org/play/#code/GYVwdgxgLglg9mABMAFASkQLkWEBbAIwFMAnRAbwFgAoRREoqEEpcAEyOBjCLZoF8gA

**Comment by mihaifm** [comment]
That makes sense, thanks for the clarification.

**Pull request merged**
