### PR TITLE
feat: update predicate for obj is Symbol.iterator

### PR DESCRIPTION
**Pull request by LviatYi**
allow iterators instead of just generators

### CODE REVIEW

**Comment by LviatYi** [comment]
## BackGround

In JavaScript, iterators are slightly different from generators.

While a generator is a specific type of iterator that comes with an additional [Symbol.iterator] function pointing to itself, this property makes generators both iterators and iterable. This dual characteristic means that a generator can be used in any context that requires an iterator or an iterable object.

[Iterators and generators | MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Iterators_and_generators)

## Feature

This pull request resolves an issue in the `from` function where it was not correctly accepting an `Iterator<T>` as indicated by its TypeScript signature.

Previously, the function checked `obj` for `[Symbol.iterator]` which limited the inputs to iterable objects (generators). This behavior may not align with the function's ability to process general iterators as intended.

## Key Changes

- **Old Check**: `typeof obj[Symbol.iterator] !== 'undefined'`
  - This check was meant to determine if `obj` was iterable. However, this constrained the function to accept only iterable objects like Arrays, Strings, or Generators.

- **New Check**: `typeof obj.next !== 'undefined'`
  - This updated check correctly targets the presence of the `next` method, which is the defining characteristic of an iterator. This aligns with the function's TypeScript signature to accept `Iterator<T>`.

## Why

- **Correct type matching**: The function now correctly accepts all iterators, not just generators, by checking next instead of [Symbol.iterator].
- **Wider acceptance**: This change increases the flexibility of the from function by allowing it to handle all qualifying iterators.

My understanding of JavaScript nuances is still growing, and this commit may deviate from the intended functionality in ways I might not fully grasp. Therefore, I would greatly appreciate any guidance or corrections. Your feedback will be invaluable to me, and I thank you in advance for your time and consideration in reviewing this fix!

**Comment by mihaifm** [comment]
Thanks, I’ll test it when I get some time. It looks good at first sight.

**Comment by mihaifm** [comment]
This change makes sense, thanks for the fix.

Following your fix we need to have a separate case for objects that only have `[Symbol.iterator]`. For example, this doesn't currently work:

    var test = new Map()
    test.set('1', 1)
    console.log(Enumerable.from(test).first()) //error

I'll try to fix this in the next version.

Also, consider disabling auto formatting when submitting PRs, you're introducing changes that are not related to the issue you're trying to fix.

**Comment by LviatYi** [comment]
Thank you very much for merging the pull request. I'm also sorry about the fact that I included a change in the commit that should have been marked as style, and I will try to avoid it as much as possible in the future.

Regarding the function of from that accepts an iterable object, I have probably completed a similar feature, please review it in a subsequent PR.

**Pull request merged**
