### PR TITLE
add localecompare when left and right is string

### PR DESCRIPTION
**Pull request by zhongchengyi**
add localecompare when use orderby , orderByDescending.
To support  locale language order.

### CODE REVIEW

**Comment by mihaifm** [comment]
Thanks, do you have an example of when this would be useful? I'll try to add a test case for it.

**Comment by zhongchengyi** [comment]
> Thanks, do you have an example of when this would be useful? I'll try to add a test case for it.

Example, I want chinese sort。
when I didn't use locale compare, the result is 
image

when I use locale compare, the result is 
image


The second one is what I want （Sort by Chinese Pinyin）。

others:
    Another way is add Enumerable.prototype.orderByChinese and Enumerable.prototype.orderByChineseDescending and other local language , which one is better ?

**Comment by zhongchengyi** [comment]
Chinese Pinyin sorting is the most desirable. The first kind of sorting, Chinese people almost never use it~~

**Comment by mihaifm** [comment]
`localeCompare` is a good solution, no need to add Chinese specific functions. I'll release a new version with this change, thanks for contributing.

**Comment by mihaifm** [comment]
Ok, so after some additional research, it seems like localeCompare uses the default system locale, so if you're using it in the browser you may get different results depending on your users' locale. Also, node doesn't include some locales (including Chinese Pinyin) unless built with ICU support.

Having said that, I think the only option for you is to pass a custom comparison function to orderBy. Unfortunately, this library doesn't support a comparison function, as opposed to [C# LINQ orderBy](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.orderby?view=netframework-4.8#System_Linq_Enumerable_OrderBy__2_System_Collections_Generic_IEnumerable___0__System_Func___0___1__System_Collections_Generic_IComparer___1__).

I will create a new issue because that's essentially what we need to fix.

**Pull request merged**
